# Generated by Django 5.2.5 on 2025-08-25 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0007_alter_certification_image_alter_programlenguage_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/projects')),
                ('gif', models.ImageField(upload_to='images/gifs')),
                ('url', models.URLField(blank=True)),
                ('lenguages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.programlenguage')),
            ],
        ),
    ]
