# Generated by Django 5.2.5 on 2025-08-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('certifications', '0007_alter_certification_image_alter_programlenguage_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
