# Generated by Django 5.2.5 on 2025-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_projects_project'),
        ('certifications', '0007_alter_certification_image_alter_programlenguage_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lenguages',
        ),
        migrations.AddField(
            model_name='project',
            name='lenguages',
            field=models.ManyToManyField(to='certifications.programlenguage'),
        ),
    ]
