# Generated by Django 5.2.5 on 2025-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_project_lenguages_project_lenguages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='largeDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
