# Generated by Django 5.2.5 on 2026-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_date_project_largedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
