# Generated by Django 5.2.5 on 2025-08-19 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='certifications/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLenguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('html', 'HTML'), ('css', 'CSS')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificarioon',
        ),
        migrations.AddField(
            model_name='certification',
            name='lenguages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.programlenguage'),
        ),
    ]
