# Generated by Django 5.2.5 on 2025-08-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_programlenguage_delete_certificarioon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlenguage',
            name='choice',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'Javascript'), ('html', 'HTML'), ('css', 'CSS')], default='Python', max_length=20),
        ),
    ]
