# Generated by Django 5.2.5 on 2025-08-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_alter_programlenguage_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlenguage',
            name='choice',
            field=models.CharField(max_length=20),
        ),
    ]
