# Generated by Django 5.2.5 on 2025-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_alter_programlenguage_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlenguage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/images'),
        ),
    ]
