# Generated by Django 5.2.5 on 2025-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_programlenguage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlenguage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/images/icons'),
        ),
    ]
