# Generated by Django 5.2.5 on 2025-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_alter_programlenguage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='images/certifications'),
        ),
        migrations.AlterField(
            model_name='programlenguage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons'),
        ),
    ]
