# Generated by Django 5.2.5 on 2025-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0007_alter_certification_image_alter_programlenguage_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
